Build and deploy medicalcals to S3 staging:
  environment: staging
  image: python:3.6-stretch
  before_script:
    - pip install awscli
    - curl -sL https://deb.nodesource.com/setup_9.x | bash -
    - apt-get install -y nodejs
    - npm install
  script:
    - npm run build
    - aws s3 cp ./build s3://$S3_BUCKET_NAME/ --recursive --acl public-read
    - aws s3 cp src/data/list.json s3://$S3_BUCKET_NAME/calculator-list.json --acl private

  only:
    - staging
  when: on_success
