image: docker:latest

stages:
  - build
  - test

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

Build and deploy medicalcalcs to S3 staging:
  stage: build

  image: python:3.6-stretch
  before_script:
    - pip install awscli
    - curl -sL https://deb.nodesource.com/setup_9.x | bash -
    - apt-get install -y nodejs
    - npm install

  script:
    - npm run build
    - aws s3 cp ./build s3://$S3_BUCKET_NAME/ --recursive --acl public-read
    - aws s3 cp src/data/list.json s3://$S3_BUCKET_NAME/calculator-list.json --acl private

  environment: staging
  only:
    - staging
  when: on_success

Test public deployment of medicalcalcs:
  stage: test
  image: alpine:3.6
  
  before_script:
    - apk add --no-cache curl grep
    
  script:
    - curl $WEB_URI | grep 'You need to enable JavaScript to run this app'
    
  environment:
    name: staging
    url: $WEB_URI
    
  only:
    - staging
