Build and deploy medicalcals to S3 staging:
  environment: staging
  image: python:3.6-stretch
  before_script:
    - pip install awscli
    - curl -sL https://deb.nodesource.com/setup_9.x | bash -
    - apt-get install -y nodejs
  script:
    - npm run build
    - aws s3 cp ./build s3://$S3_BUCKET_NAME/ --recursive
  only:
    - staging
  when: on_success
